sonar.projectKey=prova02-integration-test-Eduardo-Domingos-bessa-carvalho
sonar.organization=eduardomingos
sonar.projectName=prova02-integration-test-Eduardo-Domingos
sonar.projectVersion=1.0
sonar.sources=./src
sonar.exclusions=**/node_modules/**,**/artifacts/**,**/dist/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
